# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  controladorpedidos:
    image: controladorpedidos
    build:
      context: .
      dockerfile: src/Adapters/Driving/ControladorPedidos/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5003:5003
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
